apiVersion: v1
kind: Pod
metadata: 
  labels:
    app: kuard-config
  name: kuard-config
spec:
  containers:
  - name: test-container
    image:  gcr.io/kuar-demo/kuard-amd64:1
    env:
    - name: EXTRA_PARAM
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: extra-param
    - name: ANOTHER_PARAM
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: another-param
    volumeMounts:
    - name: config-volume
      mountPath: /config
  volumes:
    - name: config-volume
      configMap:
        name: my-config
