apiVersion: v1
kind: Service
metadata:
  name: kuard-nodeport
spec:
  externalIPs:
  - 35.232.216.103
  externalTrafficPolicy: Local
  ports:
  - nodePort: 31199 # Public IP port
    port: 8080 # Private IP port
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuard-rc-pod
  sessionAffinity: None
  type: NodePort
