apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kuard3
  name: kuard3
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:1
    name: kuard
    resources:
      requests:
        cpu: "500m" 
        memory: "128Mi"
      limits:
        cpu: "1000m"
        memory: "250Mi"
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP

