apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kuard-pod
  name: kuard-pod
spec:
  volumes:
  - name: "kuard-data"
    hostPath:
      path: "/tmp"
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:1
    name: kuard
    volumeMounts:
    - mountPath: "/data"
      name: "kuard-data"
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP

