apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    name: kuard-rs
  name: kuard-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      name: kuard-rs-pod
  template:
    metadata:
      labels:
        name: kuard-rs-pod
    spec:
      containers:
      resources:

      - image: gcr.io/kuar-demo/kuard-amd64:1
        name: kuard

