apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc2
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  selector:
    matchLabels:
      volume: database-pv2

