apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
  labels:
    volume: database-pv
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  nfs:
    server: 159.65.37.139
    path: /share

