apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv2
  labels:
    volume: database-pv2
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1Gi
  nfs:
    server: 159.65.37.139
    path: /data

